Revert "Merge branch 'master' into dyninst_unwind"
This reverts commit 649d26df4fb5dac7435b5f0fc717ebd931e33e49, reversing
changes made to 6fd22a43605c076fc59dc8e2d075defe40ecc435.

diff --git a/src/tool/hpcrun/scripts/hpcrun.in b/src/tool/hpcrun/scripts/hpcrun.in
--- a/src/tool/hpcrun/scripts/hpcrun.in
+++ b/src/tool/hpcrun/scripts/hpcrun.in
@@ -20,7 +20,6 @@ libmonitor_dir='@LIBMONITOR_RUN_DIR@'
 libunwind_dir='@LIBUNWIND_RUN_DIR@'
 papi_libdir='@OPT_PAPI_LIBPATH@'
 perfmon_libdir='@PERFMON_LIB@'
-roctracer_lib_path='@OPT_ROCM@/roctracer/lib'
 
 prog_name=hpcrun
 
@@ -134,9 +133,6 @@ Options: Profiling (Defaults shown in curly brackets {})
   -t, --trace          Generate a call path trace in addition to a call
                        path profile.
 
-  --omp-serial-only    When profiling using the OMPT interface for OpenMP,
-                       suppress all samples not in serial code.
-
   -ds, --delay-sampling
                        Delay starting sampling until the application calls
                        hpctoolkit_sampling_start().
@@ -146,15 +142,7 @@ Options: Profiling (Defaults shown in curly brackets {})
                        processes.  For each process, enable measurement
                        (of all threads) with probability <frac>; <frac> is a
                        real number (0.10) or a fraction (1/10) between 0 and 1.
-
-  -fnb <path>, --fnbounds <path>
-                       Use <path> as alternate hpcfnbounds command.
-                       (mostly for developers)
-
-  -js <num>, --jobs-symtab <num>
-                       Use <num> openmp threads for Symtab in hpcfnbounds,
-                       if Symtab supports openmp (default 1).
-
+  
   -m, --merge-threads  Merge non-overlapped threads into one virtual thread.
                        This option is to reduce the number of generated
                        profile and trace files as each thread generates its own
@@ -207,10 +195,8 @@ arg_ok()
 # others can be set now.
 
 preload_list=
-roctracer_lib=
 HPCRUN_DEBUG_FLAGS=
 HPCRUN_EVENT_LIST=
-HPCRUN_CONTROL_KNOBS=
 
 while test "x$1" != x
 do
@@ -228,12 +214,6 @@ do
 	-dd | --dynamic-debug )
 	    arg_ok "$1" || die "missing argument for $arg"
 	    export HPCRUN_DEBUG_FLAGS="$HPCRUN_DEBUG_FLAGS $1"
-	    shift
-	    ;;
-
-	-ck | --control-knob )
-	    arg_ok "$1" || die "missing argument for $arg"
-	    export HPCRUN_CONTROL_KNOBS="$HPCRUN_CONTROL_KNOBS $1"
 	    shift
 	    ;;
 
@@ -261,7 +241,6 @@ do
 		PTHREAD_WAIT* ) preload_list="${preload_list} ${hpcrun_dir}/libhpcrun_pthread.so" ;;
 		CPU_GPU_IDLE* ) preload_list="${preload_list} ${hpcrun_dir}/libhpcrun_gpu.so" ;;
 		MPI* )     preload_list="${preload_list} ${hpcrun_dir}/libhpcrun_mpi.so" ;;
-		amd-rocm*) roctracer_lib="${roctracer_lib_path}";;
 	    esac
 	    case "$HPCRUN_EVENT_LIST" in
 		'' ) HPCRUN_EVENT_LIST="$1" ;;
@@ -281,7 +260,7 @@ do
 	# --------------------------------------------------
 
  	-c | --count )
- 	    export HPCRUN_PERF_COUNT="$1"
+ 	 	export HPCRUN_PERF_COUNT="$1"
 	    shift
 	    ;;
 
@@ -289,20 +268,6 @@ do
 
 	-t | --trace )
 	    export HPCRUN_TRACE=1
-	    ;;
-
-	# --------------------------------------------------
-
-	-fnb | --fnbounds )
-	    HPCRUN_FNBOUNDS_CMD="$1"
-	    shift
-	    ;;
-
-	# --------------------------------------------------
-
-	-js | --jobs-symtab )
-	    export HPCFNBOUNDS_NUM_THREADS="$1"
-	    shift
 	    ;;
 
 	# --------------------------------------------------
@@ -315,24 +280,17 @@ do
 
 	# --------------------------------------------------
 
-	--omp-serial-only )
-	    export HPCRUN_OMP_SERIAL_ONLY=1
-	    ;;
-
-
-	# --------------------------------------------------
-
 	-r | --retain-recursion )
 	    export HPCRUN_RETAIN_RECURSION=1
 	    ;;
 
-	# --------------------------------------------------
+  # --------------------------------------------------
 
-	-m | --merge-threads )
-	    arg_ok "$1" || die "missing argument for $arg"
-	    export HPCRUN_MERGE_THREADS="$1"
-	    shift
-	    ;;
+  -m | --merge-threads )
+      arg_ok "$1" || die "missing argument for $arg"
+      export HPCRUN_MERGE_THREADS="$1"
+      shift
+      ;;
       
 	# --------------------------------------------------
 
@@ -477,23 +435,11 @@ fi
 ulimit -S -c unlimited >/dev/null 2>&1
 
 # laks 2016.10.06: add perfmon directory
-hpc_ld_library_path="${hpcrun_dir}:${papi_libdir}:${ext_dir}:${perfmon_libdir}:${roctracer_lib}"
+hpc_ld_library_path="${hpcrun_dir}:${papi_libdir}:${ext_dir}:${perfmon_libdir}"
 preload_list="${libmonitor_dir}/libmonitor.so ${preload_list}"
 preload_list="${hpcrun_dir}/libhpcrun.so ${preload_list}"
 
-# Allow fnbounds command relative to hpcfnbounds_dir.
-case "$HPCRUN_FNBOUNDS_CMD" in
-    /* ) ;;
-    '' ) HPCRUN_FNBOUNDS_CMD="${hpcfnbounds_dir}/hpcfnbounds" ;;
-    * )  HPCRUN_FNBOUNDS_CMD="${hpcfnbounds_dir}/$HPCRUN_FNBOUNDS_CMD" ;;
-esac
-
-if test ! -x "$HPCRUN_FNBOUNDS_CMD" ; then
-    echo "bad HPCRUN_FNBOUNDS_CMD command: $HPCRUN_FNBOUNDS_CMD" >&2
-    HPCRUN_FNBOUNDS_CMD="${hpcfnbounds_dir}/hpcfnbounds"
-fi
-export HPCRUN_FNBOUNDS_CMD
-
+export HPCRUN_FNBOUNDS_CMD="${hpcfnbounds_dir}/hpcfnbounds"
 export LD_LIBRARY_PATH="${hpc_ld_library_path}:${LD_LIBRARY_PATH}"
 export LD_PRELOAD="${preload_list} ${LD_PRELOAD}"
 
