Create scc branch from trunk rev 3446

diff --git a/src/tool/hpcrun/scripts/hpcrun.in b/src/tool/hpcrun/scripts/hpcrun.in
--- a/src/tool/hpcrun/scripts/hpcrun.in
+++ b/src/tool/hpcrun/scripts/hpcrun.in
@@ -5,7 +5,7 @@
 # Part of HPCToolkit (hpctoolkit.org)
 #------------------------------------
 #
-# Copyright (c) 2002-2012, Rice University.
+# Copyright (c) 2002-2010, Rice University.
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -144,16 +144,6 @@ Options: Profiling (Defaults shown in curly brackets {})
   -t, --trace          Generate a call path trace (in addition to a call
                        path profile).
 
-  -ds, --delay-sampling
-                       Delay starting sampling until the application calls
-                       hpctoolkit_sampling_start().
-
-  -f <frac>, -fp <frac>, --process-fraction <frac>
-                       Measure only a fraction <frac> of the execution's
-                       processes.  For each process, enable measurement
-                       (of all threads) with probability <frac>; <frac> is a
-                       real number (0.10) or a fraction (1/10) between 0 and 1.
-
   -o <outpath>, --output <outpath>
                        Directory for output data.
                        {hpctoolkit-<command>-measurements[-<jobid>]}
@@ -161,14 +151,6 @@ Options: Profiling (Defaults shown in curly brackets {})
                        Bug: Without a <jobid> or an output option, multiple
                        profiles of the same <command> will be placed in the
                        same output directory.
-
-  -r, --retain-recursion
-                       Normally, hpcrun will collapse (simple) recursive call chains
-                       to a single node. This option disables that behavior: all
-                       elements of a recursive call chain are recorded
-                       NOTE: If the user employs the RETCNT sample source, then this
-                             option is enabled: RETCNT implies *all* elements of
-                             call chains, including recursive elements, are recorded.
 
 NOTES:
 * hpcrun uses preloaded shared libraries to initiate profiling.  For this
@@ -196,7 +178,7 @@ arg_ok()
 # LD_PRELOAD should be delayed until we launch the program, but the
 # others can be set now.
 
-preload_list=
+memleak_preload=
 HPCRUN_DEBUG_FLAGS=
 HPCRUN_EVENT_LIST=
 
@@ -205,10 +187,10 @@ do
     arg="$1" ; shift
     case "$arg" in
 
-	# --------------------------------------------------
-
-	-md | --monitor-debug )
-	    export MONITOR_DEBUG=1
+	-a | --agent )
+	    arg_ok "$1" || die "missing argument for $arg"
+	    export HPCRUN_OPT_LUSH_AGENTS="$1"
+	    shift
 	    ;;
 
 	-d | --debug )
@@ -221,32 +203,10 @@ do
 	    shift
 	    ;;
 
-	-h | -help | --help )
-	    usage
-	    ;;
-
-	-V | --version )
-	    echo "hpcrun: A member of HPCToolkit, version $VERSION"
-	    exit 0
-	    ;;
-
-	# --------------------------------------------------
-
-	-a | --agent )
-	    arg_ok "$1" || die "missing argument for $arg"
-	    export HPCRUN_OPT_LUSH_AGENTS="$1"
-	    shift
-	    ;;
-
-	# --------------------------------------------------
-
 	-e | --event )
 	    arg_ok "$1" || die "missing argument for $arg"
 	    case "$1" in
-	        GA* )      preload_list="${preload_list} ${hpcrun_dir}/libhpcrun_ga.so" ;;
-		IO* )      preload_list="${preload_list} ${hpcrun_dir}/libhpcrun_io.so" ;;
-		MEMLEAK* ) preload_list="${preload_list} ${hpcrun_dir}/libhpcrun_memleak.so" ;;
-		MPI* )     preload_list="${preload_list} ${hpcrun_dir}/libhpcrun_mpi.so" ;;
+		MEMLEAK* ) memleak_preload="${hpcrun_dir}/libhpcrun_memleak.so" ;;
 	    esac
 	    case "$HPCRUN_EVENT_LIST" in
 		'' ) HPCRUN_EVENT_LIST="$1" ;;
@@ -255,40 +215,22 @@ do
 	    shift
 	    ;;
 
+	-h | -help | --help )
+	    usage
+	    ;;
+
 	-L | -l | --list-events )
 	    export HPCRUN_EVENT_LIST=LIST
 	    ;;
-
-	-ds | --delay-sampling )
-	    export HPCRUN_DELAY_SAMPLING=1
-	    ;;
-
-	# --------------------------------------------------
-
-	-t | --trace )
-	    export HPCRUN_TRACE=1
-	    ;;
-
-	# --------------------------------------------------
-
-	-o | --output )
-	    arg_ok "$1" || die "missing argument for $arg"
-	    export HPCRUN_OUT_PATH="$1"
-	    shift
-	    ;;
-
-	# --------------------------------------------------
-
-	-r | --retain-recursion )
-	    export HPCRUN_RETAIN_RECURSION=1
-	    ;;
-
-	# --------------------------------------------------
 
 	-lm | --low-memsize )
 	    arg_ok "$1" || die "missing argument for $arg"
 	    export HPCRUN_LOW_MEMSIZE="$1"
 	    shift
+	    ;;
+
+	-md | --monitor-debug )
+	    export MONITOR_DEBUG=1
 	    ;;
 
 	-ms | --memsize )
@@ -297,27 +239,24 @@ do
 	    shift
 	    ;;
 
-	# --------------------------------------------------
+	-o | --output )
+	    arg_ok "$1" || die "missing argument for $arg"
+	    export HPCRUN_OUT_PATH="$1"
+	    shift
+	    ;;
 
 	-q | --quiet )
 	    export HPCRUN_QUIET=1
 	    ;;
 
-	# --------------------------------------------------
-
-	-f | -fp | --process-fraction )
-	    arg_ok "$1" || die "missing argument for $arg"
-	    export HPCRUN_PROCESS_FRACTION="$1"
-	    shift
+	-t | --trace )
+	    export HPCRUN_TRACE=1
 	    ;;
 
-	-mp | --memleak-prob )
-	    arg_ok "$1" || die "missing argument for $arg"
-	    export HPCRUN_MEMLEAK_PROB="$1"
-	    shift
+	-V | --version )
+	    echo "hpcrun: A member of HPCToolkit, version $VERSION"
+	    exit 0
 	    ;;
-
-	# --------------------------------------------------
 
 	-- )
 	    break
@@ -418,12 +357,12 @@ fi
 # Enable core files.
 ulimit -S -c unlimited >/dev/null 2>&1
 
-hpc_ld_library_path="${hpcrun_dir}:${papi_libdir}"
-preload_list="${libmonitor_dir}/libmonitor.so ${preload_list}"
-preload_list="${hpcrun_dir}/libhpcrun.so ${preload_list}"
+hpc_ld_library_path="$papi_libdir"
+hpc_ld_preload="${memleak_preload} ${hpcrun_dir}/libhpcrun.so"
+hpc_ld_preload="${hpc_ld_preload} ${libmonitor_dir}/libmonitor.so"
 
 export HPCRUN_FNBOUNDS_CMD="${hpcfnbounds_dir}/hpcfnbounds"
 export LD_LIBRARY_PATH="${hpc_ld_library_path}:${LD_LIBRARY_PATH}"
-export LD_PRELOAD="${preload_list} ${LD_PRELOAD}"
+export LD_PRELOAD="${hpc_ld_preload} ${LD_PRELOAD}"
 
 exec "$@"
